### ISSUE TITLE
IR Roadmap

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#1324]
- [x] Data model https://github.com/microsoft/onnx-rewriter/pull/232 https://github.com/microsoft/onnx-rewriter/pull/257 
	- [x] Support tensor protos cleanly https://github.com/microsoft/onnx-rewriter/pull/254 https://github.com/microsoft/onnx-rewriter/pull/264
	- [ ] Support dtypes that are not in numpy
    - [ ] User defined data types
    - [x] Typing system: Unify Sequence types and Optional types https://github.com/microsoft/onnx-rewriter/pull/254 https://github.com/microsoft/onnx-rewriter/pull/264
    - [x] Tensor: implement nbytes, size and itemsize https://github.com/microsoft/onnx-rewriter/pull/254
    - [x] Use slots https://github.com/microsoft/onnx-rewriter/pull/254
    - [x] ~Shared AttrRef in functions~
    - [ ] ~Make `Function` callable.` __call__(self, *values, *attrs) -> Sequence[Value]` (but still need to get the nodes); we can also just call a function to inline it?~ Or we can "expand" it
- [ ] Use [weakref](https://docs.python.org/3/library/weakref.html#module-weakref) for some bidirectional pointers / dictionaries
    - [ ] For example, pointer in DiagnosticMessage?
- [x] Serialization to proto https://github.com/microsoft/onnx-rewriter/pull/267
    - [x] Be careful to avoid copying
- [x] Deserialization from proto https://github.com/microsoft/onnx-rewriter/pull/254 
	- [x] Test serde with the ONNX test suite https://github.com/microsoft/onnx-rewriter/pull/267
    - [x] ~User defined external data format in deserializer?~ They should handle them in a pass
    - [ ] Handle unsorted nodes
- [ ] Mutation methods for graph; sorting @justinchuby "I am here"
    - https://github.com/microsoft/onnx-rewriter/pull/273
    - [ ] Mutable protocols
    - [ ] FX graph
    - [ ] Topo sorting
    - [ ] Insertion
    - [ ] Iterator
    - [ ] Validation scenarios
        - [ ] Replace subgraph with new node
        - [ ] Build new graph from a list of nodes
        - [ ] Drop nodes
        - [ ] Insert nodes
- [ ] Initialization / mutation hooks
- [ ] Sparse tensor
- [ ] Naming authority: `must_be_named()`
- [x] Function ref in nodes (Just create new constants)
- [x] Use `rich` to pretty print objects https://github.com/microsoft/onnx-rewriter/pull/282  https://github.com/microsoft/onnx-rewriter/pull/278
- [ ] Beautiful (and easy) diagnostics!
    - [x] `__repr__` for (nested) graph and model
    - [ ] `.doctor()` method for displaying beautiful and actionable analysis in terminal. Use `rich`.
    - [ ] `Diagnosable`: define `doctor()`, `diagnose() -> DiagnosticMessage`, `add_diagnoser`, `clear_diagnosers()` for all entities in the graph
    - [ ] Extensible diagnostics with a `Diagnoser` (<-naming?) class
    - [ ] Things we can produce diagnostics for:
        * Data structure coherency: loops, nodes that do not have an owning graph, etc.
        * Spec violation: Mismatched types, unknown shape/type inputs/outputs, features unsupported by the IR version, mixed opsets etc.
        * Optimization opportunities: We can make all optimize and rewrite rules diagnosers: constant foldable, detangling nodes, redundant nodes etc.
        * The onnx.checker can be adapted as a diagnoser
    - [ ] Tools can use `diagnose()` to get messages programmatically and produce reports if they want
        - [ ] For example, the interested can build a linter out of this. But that's too much work for now.
- [ ] Use the metastore for symbolic shape inference
- [ ] Analysis interface? onnx shape inference as an analyzer?
- [ ] Creative use of meta
	- [ ] Profiling results
	- [ ] Node grouping
