### ISSUE TITLE
[rewriter] Create documentation for the optimizer and rewriter 

### ISSUE THREAD

**Issue by shubhambhokare1** [microsoft/onnxscript#1365]
Create documentation for the optimizer and rewriter, feel free to add any cases we think we need to cover

```[tasklist]
### Tasks
- [ ] Demonstrate how to utilize the passes in optimizer
- [ ] An example to show how to use the rewrite tool using the replacement by function name
- [ ] An example to show how to use the rewrite tool using the pattern replacement functionality
```

**Comment by gramalingam** [comment]
How about a section on the new IR?

**Comment by gramalingam** [comment]
All examples in documentation should also be actually run and validated (by the CI, etc.).

**Comment by justinchuby** [comment]
@shubhambhokare1 Would be nice to have a getting started page for the optimizer/rewriter to document the two-line code for running them
