### ISSUE TITLE
Tracking: ATen lib exploration

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#177]
@justinchuby is using this issue to track experiments

- [x] conditional logic involving strings
    - [x] (What does the graph look like?)
- [x] tensor as kwargs (default for onnx-inputs?)
    - [x] optional tensor inputs
- [x] return in if
- [x] generic tensor types: Aaron's PR
    - [x] union type annotations
- [x] operation on lists and tuples 
- [x] script vs non-script
- [ ] is a tensor always backed by data, or can it be symbolic? Interoperability with numpy (`__array__`)
- [x] composite subgraphs, aten if
- [x] Function calls function. Are they both in the graph? How to reuse code?
    - [x] Namespacing support for functions
    - [ ] Function calling non-script functions
    - [x] Graph builder: consider evaluator
    - [ ] If I call to function proto in the caller, will I get callee as well?
- [x] input validation. What do we need?
- [x] Data type dependent logic
    - [x] dtype reconciliation and promotion => need to be done before calling the function. 
    - [x] quantized ops
- [x] function inlining
- [ ] IR builder
    - [ ] how does it handle shape type inference when building a model proto?
