### ISSUE TITLE
Atenlib work items

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#357]
### Tasks

```[tasklist]
### Tasks
- [x] Unit test the attribute split logic (https://github.com/microsoft/onnxscript/pull/363)
- [x] Create invariance for the split logic and move it into onnxscript
- [x] Unit test public interface for the graph building classes
- [x] https://github.com/microsoft/onnxscript/issues/269
- [x] Move unit tests inside the source directory
- [x] Test op.Constant (https://github.com/microsoft/onnxscript/pull/363)
- [x] Test trace only ops - test in exporter (https://github.com/pytorch/pytorch/pull/92894)
- [x] Test multi output ops - test in exporter (https://github.com/pytorch/pytorch/pull/92894)
- [x] Support setting torch.Value names and shapes; verify the input data mapping works
- [ ] https://github.com/microsoft/onnxscript/issues/388
- [x] Add cast modes to ops like add
- [x] https://github.com/microsoft/onnxscript/issues/390
- [x] https://github.com/microsoft/onnxscript/issues/397
- [x] https://github.com/microsoft/onnxscript/issues/387
- [ ] https://github.com/microsoft/onnxscript/issues/386
- [x] https://github.com/microsoft/onnxscript/issues/385
- [x] https://github.com/microsoft/onnxscript/issues/389
- [x] https://github.com/microsoft/onnxscript/issues/258
- [ ] https://github.com/microsoft/onnxscript/issues/310
- [ ] https://github.com/microsoft/onnxscript/issues/209
- [x] https://github.com/microsoft/onnxscript/issues/393
- [x] https://github.com/microsoft/onnxscript/issues/398
- [x] https://github.com/microsoft/onnxscript/issues/418
- [x] https://github.com/microsoft/onnxscript/issues/417
- [x] https://github.com/microsoft/onnxscript/issues/419
- [x] https://github.com/microsoft/onnxscript/issues/424
- [ ] https://github.com/microsoft/onnxscript/issues/425
- [x] https://github.com/microsoft/onnxscript/issues/475
- [ ] https://github.com/microsoft/onnxscript/issues/465
- [x] https://github.com/microsoft/onnxscript/issues/481
- [ ] https://github.com/microsoft/onnxscript/issues/493
- [ ] https://github.com/microsoft/onnxscript/issues/496
- [x] https://github.com/microsoft/onnxscript/issues/497
- [x] https://github.com/microsoft/onnxscript/pull/528
- [x] https://github.com/onnx/onnx/issues/5019
- [x] https://github.com/microsoft/onnxscript/issues/564
- [x] https://github.com/microsoft/onnxscript/issues/590
- [ ] https://github.com/microsoft/onnxscript/issues/611
- [ ] https://github.com/microsoft/onnxscript/issues/629
- [x] https://github.com/microsoft/onnxscript/issues/476
- [x] https://github.com/microsoft/onnxscript/issues/630
- [x] https://github.com/microsoft/onnxscript/issues/693
- [ ] https://github.com/microsoft/onnxscript/issues/706
- [ ] https://github.com/microsoft/onnxscript/issues/707
- [ ] https://github.com/microsoft/onnxscript/issues/708
- [x] https://github.com/microsoft/onnxscript/issues/713
- [ ] https://github.com/microsoft/onnxscript/issues/855
- [ ] https://github.com/microsoft/onnxscript/issues/834
- [ ] https://github.com/microsoft/onnxscript/issues/841
- [x] https://github.com/microsoft/onnxscript/issues/865
- [x] https://github.com/microsoft/onnxscript/issues/872
- [ ] https://github.com/microsoft/onnxscript/issues/917
- [ ] https://github.com/microsoft/onnxscript/issues/945
- [ ] https://github.com/microsoft/onnxscript/issues/960
- [ ] https://github.com/microsoft/onnxscript/issues/984
- [ ] https://github.com/microsoft/onnxscript/issues/999
- [ ] https://github.com/microsoft/onnxscript/issues/1016
- [ ] https://github.com/microsoft/onnxscript/issues/1218
- [ ] https://github.com/microsoft/onnxscript/issues/415
```

**Comment by justinchuby** [comment]
Filed bugs discovered by the atenlib work since 3/24: https://github.com/orgs/microsoft/projects/642/views/
