### ISSUE TITLE
[torchlib] float8 support

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#984]
https://github.com/pytorch/pytorch/blob/main/test/quantization/core/experimental/test_float8.py
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/onnxscript/issues/997
- [ ] https://github.com/microsoft/onnxscript/issues/998
- [ ] https://github.com/pytorch/pytorch/pull/106883
- [ ] https://github.com/pytorch/pytorch/pull/106379
- [ ] https://github.com/pytorch/pytorch/pull/107962
```
